// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: FalconryScale

#ifndef _FALCONRYSCALE_UI_H
#define _FALCONRYSCALE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
void ui_event_Loading_Screen(lv_event_t * e);
extern lv_obj_t * ui_Loading_Screen;
extern lv_obj_t * ui_Wrapper_Loading_Page;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Spinner1;
// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Wrapper_Home;
void ui_event_LoadingBtn(lv_event_t * e);
extern lv_obj_t * ui_LoadingBtn;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_logo_png);    // assets/Logo/Logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
