// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: FalconryScale

#include "ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wrapper_Home = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_Wrapper_Home);
    lv_obj_set_width(ui_Wrapper_Home, lv_pct(100));
    lv_obj_set_height(ui_Wrapper_Home, lv_pct(100));
    lv_obj_set_align(ui_Wrapper_Home, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wrapper_Home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Wrapper_Home, lv_color_hex(0xE9EAF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wrapper_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingBtn = lv_btn_create(ui_Wrapper_Home);
    lv_obj_set_width(ui_LoadingBtn, 100);
    lv_obj_set_height(ui_LoadingBtn, 100);
    lv_obj_set_align(ui_LoadingBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoadingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LoadingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_LoadingBtn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Go Back");

    lv_obj_add_event_cb(ui_LoadingBtn, ui_event_LoadingBtn, LV_EVENT_ALL, NULL);

}
