// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: FalconryScale-IoT

#include "ui.h"


void ui_loading_screen_screen_init(void)
{
    ui_loading_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_loading_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loading_screen_container_main_wrapper = lv_obj_create(ui_loading_screen);
    lv_obj_remove_style_all(ui_loading_screen_container_main_wrapper);
    lv_obj_set_width(ui_loading_screen_container_main_wrapper, lv_pct(100));
    lv_obj_set_height(ui_loading_screen_container_main_wrapper, lv_pct(100));
    lv_obj_set_align(ui_loading_screen_container_main_wrapper, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_loading_screen_container_main_wrapper,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loading_screen_container_main_wrapper, lv_color_hex(0x191C2F),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loading_screen_container_main_wrapper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loading_screen_image_logo = lv_img_create(ui_loading_screen_container_main_wrapper);
    lv_img_set_src(ui_loading_screen_image_logo, &ui_img_logo_logo_png);
    lv_obj_set_width(ui_loading_screen_image_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loading_screen_image_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loading_screen_image_logo, 0);
    lv_obj_set_y(ui_loading_screen_image_logo, -50);
    lv_obj_set_align(ui_loading_screen_image_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading_screen_image_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_loading_screen_image_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loading_screen_spinner_spinner = lv_spinner_create(ui_loading_screen_container_main_wrapper, 1000, 90);
    lv_obj_set_width(ui_loading_screen_spinner_spinner, 40);
    lv_obj_set_height(ui_loading_screen_spinner_spinner, 40);
    lv_obj_set_x(ui_loading_screen_spinner_spinner, 0);
    lv_obj_set_y(ui_loading_screen_spinner_spinner, 50);
    lv_obj_set_align(ui_loading_screen_spinner_spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_loading_screen_spinner_spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_loading_screen_spinner_spinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loading_screen_spinner_spinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_loading_screen_spinner_spinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_loading_screen_spinner_spinner, lv_color_hex(0xFA4100),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loading_screen_spinner_spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_loading_screen_spinner_spinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_loading_screen, ui_event_loading_screen, LV_EVENT_ALL, NULL);

}
