// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: FalconryScale

#include "ui.h"

void ui_Loading_Screen_screen_init(void)
{
    ui_Loading_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Loading_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wrapper_Loading_Page = lv_obj_create(ui_Loading_Screen);
    lv_obj_remove_style_all(ui_Wrapper_Loading_Page);
    lv_obj_set_width(ui_Wrapper_Loading_Page, lv_pct(100));
    lv_obj_set_height(ui_Wrapper_Loading_Page, lv_pct(100));
    lv_obj_set_align(ui_Wrapper_Loading_Page, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wrapper_Loading_Page, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Wrapper_Loading_Page, lv_color_hex(0x191C2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wrapper_Loading_Page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Wrapper_Loading_Page, lv_color_hex(0x08090F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Wrapper_Loading_Page, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Wrapper_Loading_Page);
    lv_img_set_src(ui_Image1, &ui_img_logo_logo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -50);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Wrapper_Loading_Page, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 40);
    lv_obj_set_height(ui_Spinner1, 40);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 50);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFA4100), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Loading_Screen, ui_event_Loading_Screen, LV_EVENT_ALL, NULL);

}
