// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: FalconryScale-IoT

#include "ui.h"

void ui_weight_screen_screen_init(void)
{
    ui_weight_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weight_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weight_screen_container_main_wrapper = lv_obj_create(ui_weight_screen);
    lv_obj_remove_style_all(ui_weight_screen_container_main_wrapper);
    lv_obj_set_width(ui_weight_screen_container_main_wrapper, lv_pct(100));
    lv_obj_set_height(ui_weight_screen_container_main_wrapper, lv_pct(100));
    lv_obj_set_align(ui_weight_screen_container_main_wrapper, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weight_screen_container_main_wrapper,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weight_screen_tabview_tabview1 = lv_tabview_create(ui_weight_screen_container_main_wrapper, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_weight_screen_tabview_tabview1, lv_pct(100));
    lv_obj_set_height(ui_weight_screen_tabview_tabview1, lv_pct(100));
    lv_obj_set_align(ui_weight_screen_tabview_tabview1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weight_screen_tabview_tabview1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_weight_screen_tabpage_weight = lv_tabview_add_tab(ui_weight_screen_tabview_tabview1, "Weight");

    ui_weight_screen_container_container3 = lv_obj_create(ui_weight_screen_tabpage_weight);
    lv_obj_remove_style_all(ui_weight_screen_container_container3);
    lv_obj_set_width(ui_weight_screen_container_container3, 88);
    lv_obj_set_height(ui_weight_screen_container_container3, 46);
    lv_obj_set_x(ui_weight_screen_container_container3, 0);
    lv_obj_set_y(ui_weight_screen_container_container3, -40);
    lv_obj_set_align(ui_weight_screen_container_container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_weight_screen_container_container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_weight_screen_container_container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_weight_screen_container_container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weight_screen_label_value = lv_label_create(ui_weight_screen_container_container3);
    lv_obj_set_width(ui_weight_screen_label_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weight_screen_label_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weight_screen_label_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weight_screen_label_value, "00");

    ui_weight_screen_label_grams = lv_label_create(ui_weight_screen_container_container3);
    lv_obj_set_width(ui_weight_screen_label_grams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weight_screen_label_grams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weight_screen_label_grams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weight_screen_label_grams, "gr");

    ui_weight_screen_button_button1 = lv_btn_create(ui_weight_screen_tabpage_weight);
    lv_obj_set_width(ui_weight_screen_button_button1, 100);
    lv_obj_set_height(ui_weight_screen_button_button1, 50);
    lv_obj_set_x(ui_weight_screen_button_button1, 0);
    lv_obj_set_y(ui_weight_screen_button_button1, 60);
    lv_obj_set_align(ui_weight_screen_button_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weight_screen_button_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_weight_screen_button_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weight_screen_button_button1, lv_color_hex(0xFF4A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weight_screen_button_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weight_screen_label_label2 = lv_label_create(ui_weight_screen_button_button1);
    lv_obj_set_width(ui_weight_screen_label_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weight_screen_label_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weight_screen_label_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weight_screen_label_label2, "Tare");

    ui_weight_screen_tabpage_settings = lv_tabview_add_tab(ui_weight_screen_tabview_tabview1, "Settings");

    ui_weight_screen_button_button2 = lv_btn_create(ui_weight_screen_tabpage_settings);
    lv_obj_set_width(ui_weight_screen_button_button2, 100);
    lv_obj_set_height(ui_weight_screen_button_button2, 50);
    lv_obj_set_align(ui_weight_screen_button_button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weight_screen_button_button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_weight_screen_button_button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weight_screen_button_button2, lv_color_hex(0xFAA700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weight_screen_button_button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weight_screen_label_go_back = lv_label_create(ui_weight_screen_button_button2);
    lv_obj_set_width(ui_weight_screen_label_go_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weight_screen_label_go_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weight_screen_label_go_back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weight_screen_label_go_back, "Reload");

    lv_obj_add_event_cb(ui_weight_screen_button_button1, ui_event_weight_screen_button_button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weight_screen_button_button2, ui_event_weight_screen_button_button2, LV_EVENT_ALL, NULL);

}
