// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: FalconryScale-IoT

#ifndef _FALCONRYSCALE_IOT_UI_H
#define _FALCONRYSCALE_IOT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// #include "lv_i18n.h"
#include "ui/ui_helpers.h"
#include "ui/ui_events.h"

// SCREEN: ui_loading_screen
void ui_loading_screen_screen_init(void);
void ui_event_loading_screen(lv_event_t * e);
extern lv_obj_t * ui_loading_screen;
extern lv_obj_t * ui_loading_screen_container_main_wrapper;
extern lv_obj_t * ui_loading_screen_image_logo;
extern lv_obj_t * ui_loading_screen_spinner_spinner;
// SCREEN: ui_weight_screen
void ui_weight_screen_screen_init(void);
extern lv_obj_t * ui_weight_screen;
extern lv_obj_t * ui_weight_screen_container_main_wrapper;
extern lv_obj_t * ui_weight_screen_tabview_tabview1;
extern lv_obj_t * ui_weight_screen_tabpage_weight;
extern lv_obj_t * ui_weight_screen_container_container3;
extern lv_obj_t * ui_weight_screen_label_value;
extern lv_obj_t * ui_weight_screen_label_grams;
void ui_event_weight_screen_button_button1(lv_event_t * e);
extern lv_obj_t * ui_weight_screen_button_button1;
extern lv_obj_t * ui_weight_screen_label_label2;
extern lv_obj_t * ui_weight_screen_tabpage_settings;
void ui_event_weight_screen_button_button2(lv_event_t * e);
extern lv_obj_t * ui_weight_screen_button_button2;
extern lv_obj_t * ui_weight_screen_label_go_back;
extern lv_obj_t * ui_startevents____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_logo_png);    // assets/Logo/Logo.png


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif