// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

//#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
void ui_event_Loading_Screen(lv_event_t * e);
extern lv_obj_t * ui_Loading_Screen;
extern lv_obj_t * ui_Loading_Screen_Wrapper;
extern lv_obj_t * ui_Loading_Screen_Logo;
extern lv_obj_t * ui_Loading_Screen_Spinner;
// SCREEN: ui_Dashboard
void ui_Dashboard_screen_init(void);
extern lv_obj_t * ui_Dashboard;
extern lv_obj_t * ui_Dashboard_Container2;
extern lv_obj_t * ui_Dashboard_TabView1;
extern lv_obj_t * ui_Dashboard_weight;
extern lv_obj_t * ui_Dashboard_Label2;
extern lv_obj_t * ui_Dashboard_Gramms;
extern lv_obj_t * ui_Dashboard_raptors;
extern lv_obj_t * ui_Dashboard_settings;
void ui_event_Dashboard_Button_Wrapper(lv_event_t * e);
extern lv_obj_t * ui_Dashboard_Button_Wrapper;
extern lv_obj_t * ui_Dashboard_Reload_Button;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_png);    // assets/Logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
