// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
void ui_event_Loading_Screen(lv_event_t * e);
lv_obj_t * ui_Loading_Screen;
lv_obj_t * ui_Loading_Screen_Wrapper;
lv_obj_t * ui_Loading_Screen_Logo;
lv_obj_t * ui_Loading_Screen_Spinner;


// SCREEN: ui_Dashboard
void ui_Dashboard_screen_init(void);
lv_obj_t * ui_Dashboard;
lv_obj_t * ui_Dashboard_Container2;
lv_obj_t * ui_Dashboard_TabView1;
lv_obj_t * ui_Dashboard_weight;
lv_obj_t * ui_Dashboard_Label2;
lv_obj_t * ui_Dashboard_Gramms;
lv_obj_t * ui_Dashboard_raptors;
lv_obj_t * ui_Dashboard_settings;
void ui_event_Dashboard_Button_Wrapper(lv_event_t * e);
lv_obj_t * ui_Dashboard_Button_Wrapper;
lv_obj_t * ui_Dashboard_Reload_Button;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Loading_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Dashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_Dashboard_screen_init);
    }
}
void ui_event_Dashboard_Button_Wrapper(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Loading_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Loading_Screen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Loading_Screen_screen_init();
    ui_Dashboard_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Loading_Screen);
}
