// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Dashboard_screen_init(void)
{
    ui_Dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dashboard_Container2 = lv_obj_create(ui_Dashboard);
    lv_obj_remove_style_all(ui_Dashboard_Container2);
    lv_obj_set_width(ui_Dashboard_Container2, lv_pct(100));
    lv_obj_set_height(ui_Dashboard_Container2, lv_pct(100));
    lv_obj_set_align(ui_Dashboard_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Dashboard_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dashboard_TabView1 = lv_tabview_create(ui_Dashboard_Container2, LV_DIR_BOTTOM, 50);
    lv_obj_set_width(ui_Dashboard_TabView1, lv_pct(100));
    lv_obj_set_height(ui_Dashboard_TabView1, lv_pct(100));
    lv_obj_set_align(ui_Dashboard_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Dashboard_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Dashboard_weight = lv_tabview_add_tab(ui_Dashboard_TabView1, "Weight");
    lv_obj_set_flex_flow(ui_Dashboard_weight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Dashboard_weight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Dashboard_Label2 = lv_label_create(ui_Dashboard_weight);
    lv_obj_set_width(ui_Dashboard_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dashboard_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dashboard_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dashboard_Label2, "00");

    ui_Dashboard_Gramms = lv_label_create(ui_Dashboard_weight);
    lv_obj_set_width(ui_Dashboard_Gramms, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dashboard_Gramms, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dashboard_Gramms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dashboard_Gramms, "gr");

    ui_Dashboard_raptors = lv_tabview_add_tab(ui_Dashboard_TabView1, "Raptors");

    ui_Dashboard_settings = lv_tabview_add_tab(ui_Dashboard_TabView1, "Settings");

    ui_Dashboard_Button_Wrapper = lv_btn_create(ui_Dashboard_settings);
    lv_obj_set_width(ui_Dashboard_Button_Wrapper, 100);
    lv_obj_set_height(ui_Dashboard_Button_Wrapper, 50);
    lv_obj_set_align(ui_Dashboard_Button_Wrapper, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dashboard_Button_Wrapper, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Dashboard_Button_Wrapper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Dashboard_Button_Wrapper, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Dashboard_Button_Wrapper, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);
    ui_object_set_themeable_style_property(ui_Dashboard_Button_Wrapper, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Secondary);
    ui_object_set_themeable_style_property(ui_Dashboard_Button_Wrapper, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Secondary);

    ui_Dashboard_Reload_Button = lv_label_create(ui_Dashboard_Button_Wrapper);
    lv_obj_set_width(ui_Dashboard_Reload_Button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dashboard_Reload_Button, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dashboard_Reload_Button, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Dashboard_Button_Wrapper, ui_event_Dashboard_Button_Wrapper, LV_EVENT_ALL, NULL);

}
