// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: FalconryScale-IoT

#include "ui.h"

void function_tare(lv_event_t * e)
{
	// Your code here
}
