// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Primary[3] = {0xFA4100, 0xFA4100, 0xFA4100};
const ui_theme_variable_t _ui_theme_alpha_Primary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Secondary[3] = {0x191C2F, 0x191C2F, 0x191C2F};
const ui_theme_variable_t _ui_theme_alpha_Secondary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Base[3] = {0x1D1D1D, 0xFFFFFF, 0x1D1D1D};
const ui_theme_variable_t _ui_theme_alpha_Base[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Text[3] = {0xFFFFFF, 0x1D1D1D, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_Text[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

